name: ASCII Workflow

on:
  - push

jobs: 
    eugene_kofi: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Execute Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh